apiVersion: apps/v1
kind: Deployment
metadata:
  name: katypa-app-deployment
spec:
  
  replicas: 2
  
  selector:
    matchLabels:
      app: katypa-app
  
  template:
    metadata:
      labels:
        app: katypa-app
    spec:
      containers:
      - name: katypa-app-container
        image: yfi9a/katybasystem:1.0.0
        resources:
          limits: 
            cpu: 250m
            memory : 500Mi
            
        ports:
        - containerPort: 8000
