# Generated by Django 2.1.5 on 2019-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='reward_days',
            field=models.IntegerField(),
        ),
    ]
