# Generated by Django 2.1.5 on 2019-02-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0003_auto_20190219_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierpunishments',
            name='punishment',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Punishment',
        ),
    ]
