# Generated by Django 2.1.5 on 2019-02-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0004_auto_20190220_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='current_punishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='armydbapp.SoldierPunishments'),
        ),
    ]
