# Generated by Django 2.1.5 on 2019-02-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0005_soldier_current_punishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='current_army_unit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
