# Generated by Django 2.1.5 on 2019-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0006_soldier_current_army_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='is_at_punishment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
