# Generated by Django 2.1.5 on 2019-03-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0007_auto_20190220_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_awaiting_trial',
            field=models.BooleanField(default=False),
        ),
    ]
