# Generated by Django 2.1.5 on 2019-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0008_soldier_is_awaiting_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='soldier_img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='\\static\x07rmydbapp\\soldier-img-upload'),
        ),
    ]
