# Generated by Django 2.1.5 on 2019-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0010_auto_20190310_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='reward_date',
            field=models.DateField(auto_now=True),
        ),
    ]
