# Generated by Django 2.1.5 on 2019-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0011_auto_20190310_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='reward_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
