# Generated by Django 2.1.5 on 2019-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0012_auto_20190310_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldier',
            name='outing_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
