# Generated by Django 2.1.5 on 2019-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0013_auto_20190310_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
