# Generated by Django 2.1.5 on 2019-03-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0014_soldier_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_in_mission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldier',
            name='mission_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
