# Generated by Django 2.1.5 on 2019-04-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0015_auto_20190310_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='soldier_img',
        ),
        migrations.AddField(
            model_name='soldier',
            name='speciality',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
