# Generated by Django 2.1.5 on 2019-04-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0016_auto_20190425_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='speciality',
            field=models.CharField(blank=True, default='مراقب جوي', max_length=50, null=True),
        ),
    ]
