# Generated by Django 2.1.5 on 2019-04-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0018_remove_soldier_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='speciality',
            field=models.CharField(blank=True, default='مراقب جوي', max_length=50, null=True),
        ),
    ]
