# Generated by Django 2.1.5 on 2019-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0019_soldier_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='adress',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
