# Generated by Django 2.1.5 on 2019-04-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0020_soldier_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierarmyunits',
            name='army_unit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
