# Generated by Django 2.1.5 on 2019-04-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0022_soldier_vacation_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='id_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
