# Generated by Django 2.1.5 on 2019-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0023_soldier_id_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_at_vacation_sick',
            field=models.BooleanField(default=False),
        ),
    ]
