# Generated by Django 2.1.5 on 2019-05-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0024_soldier_is_at_vacation_sick'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
