# Generated by Django 2.1.5 on 2019-06-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0026_promotion_vacations'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='reason_awaiting_trial',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
