# Generated by Django 2.1.5 on 2019-06-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0027_soldier_reason_awaiting_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='days_absent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
