# Generated by Django 2.1.5 on 2019-06-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0028_soldier_days_absent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArmyUnit',
        ),
    ]
