# Generated by Django 2.1.5 on 2019-06-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0029_delete_armyunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='soldier_img',
            field=models.ImageField(blank=True, null=True, upload_to='soldiers_imgs/'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='current_punishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='armydbapp.SoldierPunishments'),
        ),
    ]
