# Generated by Django 2.1.5 on 2019-06-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0030_auto_20190608_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='job',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='work_assigned',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='zucchini',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
