# Generated by Django 2.1.5 on 2019-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0031_auto_20190609_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='a5eir_sarfaya',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='cultural_level',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='educational_degree',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='remarks',
            field=models.CharField(blank=True, max_length=2560, null=True),
        ),
    ]
