# Generated by Django 2.1.5 on 2019-07-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0032_auto_20190707_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('officer_img', models.ImageField(blank=True, null=True, upload_to='soldiers_imgs/')),
                ('officer_id', models.IntegerField(unique=True)),
                ('service_start_date', models.DateField()),
                ('service_end_date', models.DateField()),
                ('current_army_unit', models.CharField(blank=True, max_length=256, null=True)),
                ('speciality', models.CharField(blank=True, default='دفاع جوي', max_length=50, null=True)),
                ('adress', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('id_tag', models.CharField(blank=True, max_length=256, null=True)),
                ('is_at_vacation', models.BooleanField(default=False)),
                ('is_at_vacation_sick', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('reward_days', models.IntegerField(blank=True, null=True)),
                ('is_at_punishment', models.BooleanField(default=False)),
                ('is_awaiting_trial', models.BooleanField(default=False)),
                ('reason_awaiting_trial', models.CharField(blank=True, max_length=1200, null=True)),
                ('is_out', models.BooleanField(default=False)),
                ('outing_type', models.CharField(blank=True, max_length=256, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('days_absent', models.CharField(blank=True, max_length=256, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('is_in_mission', models.BooleanField(default=False)),
                ('mission_type', models.CharField(blank=True, max_length=256, null=True)),
                ('work_assigned', models.CharField(blank=True, max_length=256, null=True)),
                ('zucchini', models.CharField(blank=True, max_length=256, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2560, null=True)),
                ('educational_degree', models.CharField(blank=True, max_length=256, null=True)),
                ('current_punishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='armydbapp.SoldierPunishments')),
            ],
        ),
        migrations.CreateModel(
            name='Officer_Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_days', models.IntegerField(blank=True, null=True)),
                ('reward_date', models.DateField(auto_now=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerArmyUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_unit', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_rank', models.CharField(blank=True, default='ملازم', max_length=256, null=True)),
                ('promotion_date', models.DateField(blank=True, default=None, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerPunishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerVacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sub_officer_img', models.ImageField(blank=True, null=True, upload_to='soldiers_imgs/')),
                ('sub_officer_id', models.IntegerField(unique=True)),
                ('service_start_date', models.DateField()),
                ('service_end_date', models.DateField()),
                ('current_army_unit', models.CharField(blank=True, max_length=256, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('adress', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('id_tag', models.CharField(blank=True, max_length=256, null=True)),
                ('is_at_vacation', models.BooleanField(default=False)),
                ('is_at_vacation_sick', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('reward_days', models.IntegerField(blank=True, null=True)),
                ('is_at_punishment', models.BooleanField(default=False)),
                ('is_awaiting_trial', models.BooleanField(default=False)),
                ('reason_awaiting_trial', models.CharField(blank=True, max_length=1200, null=True)),
                ('is_out', models.BooleanField(default=False)),
                ('outing_type', models.CharField(blank=True, max_length=256, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('days_absent', models.CharField(blank=True, max_length=256, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('is_in_mission', models.BooleanField(default=False)),
                ('mission_type', models.CharField(blank=True, max_length=256, null=True)),
                ('work_assigned', models.CharField(blank=True, max_length=256, null=True)),
                ('zucchini', models.CharField(blank=True, max_length=256, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2560, null=True)),
                ('educational_degree', models.CharField(blank=True, max_length=256, null=True)),
                ('current_punishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='armydbapp.SoldierPunishments')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_officer_Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_officer_rank', models.CharField(blank=True, default='عريف', max_length=256, null=True)),
                ('promotion_date', models.DateField(blank=True, default=None, null=True)),
                ('sub_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Sub_officer')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_officer_Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_days', models.IntegerField(blank=True, null=True)),
                ('reward_date', models.DateField(auto_now=True, null=True)),
                ('sub_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Sub_officer')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_officer_Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('sub_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Sub_officer')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_officerArmyUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_unit', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('sub_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Sub_officer')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_officerPunishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sub_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armydbapp.Sub_officer')),
            ],
        ),
    ]
