# Generated by Django 2.1.5 on 2019-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0033_officer_officer_rewards_officerarmyunits_officerpromotion_officerpunishments_officervacations_sub_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='battalion_first_in_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rank', models.CharField(max_length=256)),
                ('officer_id', models.IntegerField(unique=True)),
                ('exp_number', models.IntegerField(unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='battalion_operation_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rank', models.CharField(max_length=256)),
                ('officer_id', models.IntegerField(unique=True)),
                ('exp_number', models.IntegerField(unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='battalion_second_in_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rank', models.CharField(max_length=256)),
                ('officer_id', models.IntegerField(unique=True)),
                ('exp_number', models.IntegerField(unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_commander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rank', models.CharField(max_length=256)),
                ('officer_id', models.IntegerField(unique=True)),
                ('exp_number', models.IntegerField(unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='exp_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
