# Generated by Django 2.1.5 on 2019-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0034_auto_20190710_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='educational_degree',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='is_out',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='outing_type',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='service_end_date',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='zucchini',
        ),
        migrations.RemoveField(
            model_name='sub_officer',
            name='educational_degree',
        ),
        migrations.RemoveField(
            model_name='sub_officer',
            name='is_out',
        ),
        migrations.RemoveField(
            model_name='sub_officer',
            name='outing_type',
        ),
        migrations.RemoveField(
            model_name='sub_officer',
            name='service_end_date',
        ),
        migrations.RemoveField(
            model_name='sub_officer',
            name='work_assigned',
        ),
        migrations.RemoveField(
            model_name='sub_officer',
            name='zucchini',
        ),
        migrations.AlterField(
            model_name='officer',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_officer',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
