# Generated by Django 2.1.5 on 2019-07-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0036_company_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='armydbapp.Company'),
        ),
    ]
