# Generated by Django 2.1.5 on 2019-07-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0037_auto_20190715_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='rank',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sub_officer',
            name='rank',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
