# Generated by Django 2.1.5 on 2019-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0038_auto_20190716_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='exp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
