# Generated by Django 2.1.5 on 2019-09-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0040_auto_20190815_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='current_punishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='armydbapp.OfficerPunishments'),
        ),
    ]
