# Generated by Django 2.1.5 on 2023-10-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armydbapp', '0041_auto_20190908_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='point',
            field=models.CharField(default='  -  ', max_length=256),
        ),
    ]
